### ISSUE TITLE
Bucket region sa-east-1

### ISSUE THREAD

**Issue by Jhara** [aesopwolf/s3-basic-auth#1]
I have a bucket in the region sa-east-1, This code works for me?

**Comment by MasaGon** [comment]
Same problem for me with ap-northeast-1. Some fixed code with 'us-east-1' seems to exist.
https://github.com/aesopwolf/s3-basic-auth/blob/master/lib/generate-presigned-url.js#L13

**Comment by aesopwolf** [comment]
My mistake, I didn't realize S3 had different regions. I'd be willing to accept a PR that allows you to override that config!

**Comment by aesopwolf** [comment]
This was just fixed over here https://github.com/aesopwolf/s3-basic-auth/pull/6
